const fs = require('fs');
const path = require('path');

// Define paths for source assets and generated map files
const assetsDir = path.join(__dirname, 'src', 'assets');
const iconMapJsPath = path.join(__dirname, 'src', 'iconMap.js');
const iconMapDartPath = path.join(__dirname, 'flutter_lib', 'lib', 'icon_map.dart');
const flutterAssetsDir = 'assets/icons'; // Relative path for Flutter assets within its package

/**
 * Generates icon map files for both JavaScript and Dart.
 * It reads asset filenames, converts them to PascalCase icon names,
 * and creates mappings to their respective relative paths.
 *
 * @returns {Promise<void>} A promise that resolves when both files are written, or rejects on error.
 */
async function generateIconMaps() {
  return new Promise((resolve, reject) => {
    fs.readdir(assetsDir, (err, files) => {
      console.log('Reading assets from directory:', assetsDir);
      console.log('Files found:', files);
      if (err) {
        console.error('Error reading assets directory:', err);
        return reject(err);
      }

      const generatedIconNames = new Set(); // To track unique icon names
      // --- Start of JS Content Generation ---
      let jsImportStatements = '';
      let jsExportMap = 'export const iconMap = {\n';
      // --- End of JS Content Generation ---

      // --- Start of Dart Content Generation (preserved) ---
      let dartMapContent = '/// This file is generated by generateIconMap.js. Do not modify directly.\n';
      dartMapContent += 'class IconMap {\n';
      dartMapContent += '  static const Map<String, String> iconMap = {\n';
      // --- End of Dart Content Generation ---

      files.forEach(file => {
        console.log('Processing file:', file);
        const fileNameWithoutExt = file.split('.').slice(0, -1).join('.');
        console.log('File name without extension:', fileNameWithoutExt);
        // Convert filename to PascalCase for icon name (e.g., "my-icon.webp" -> "MyIcon")
        let baseIconName = fileNameWithoutExt
          .replace(/[^a-zA-Z0-9]+(.)?/g, (match, chr) => chr ? chr.toUpperCase() : '')
          .replace(/^./, (match) => match.toUpperCase());
        
        let iconName = baseIconName;
        let counter = 1;
        while (generatedIconNames.has(iconName)) {
          counter++;
          iconName = `${baseIconName}_${counter}`;
        }
        generatedIconNames.add(iconName);
        console.log('Generated unique icon name:', iconName);

        // --- JS Specific Logic ---
        // Clean iconName to create a valid JavaScript variable name
        const rawAssetVarName = iconName.replace(/[^a-zA-Z0-9]/g, '');
        const assetVarName = (isNaN(parseInt(rawAssetVarName.charAt(0))) ? '' : '_') + rawAssetVarName + 'Asset';

        jsImportStatements += `import ${assetVarName} from './assets/${file}';\n`;
        jsExportMap += `  "${iconName}": ${assetVarName},\n`;
        // --- End of JS Specific Logic ---

        // --- Dart Specific Logic (preserved) ---
        dartMapContent += `    '${iconName}': '${flutterAssetsDir}/${file}',\n`;
        // --- End of Dart Specific Logic ---
      });

      // --- Finalize JS Content ---
      let jsMapContent = jsImportStatements + '\n' + jsExportMap + '};';
      // --- Finalize JS Content ---

      // --- Finalize Dart Content (preserved) ---
      dartMapContent += '  };\n';
      dartMapContent += '}\n';
      // --- Finalize Dart Content ---
      
      
            console.log('Generated jsMapContent:\n', jsMapContent);
            console.log('Generated dartMapContent:\n', dartMapContent);
      
            const writePromises = [];
      // Write JavaScript iconMap.js
      writePromises.push(new Promise((res, rej) => {
        fs.writeFile(iconMapJsPath, jsMapContent, (err) => {
          if (err) {
            console.error('Error writing iconMap.js:', err);
            return rej(err);
          }
          console.log('iconMap.js generated successfully!');
          res();
        });
      }));

      // Write Dart icon_map.dart
      writePromises.push(new Promise((res, rej) => {
        fs.writeFile(iconMapDartPath, dartMapContent, (err) => {
          if (err) {
            console.error('Error writing icon_map.dart:', err);
            return rej(err);
          }
          console.log('icon_map.dart generated successfully!');
          res();
        });
      }));

      Promise.all(writePromises).then(() => {
        console.log('All icon map files generated successfully!');
        resolve();
      }).catch(reject);
    });
  });
}

// Execute generateIconMaps if the script is run directly (e.g., via `node generateIconMap.js`)
if (require.main === module) {
  generateIconMaps().catch(error => {
    // Log error and exit with a non-zero code if generation fails
    console.error('Failed to generate icon maps:', error);
    process.exit(1);
  });
}

// Export the function for testing and programmatic use
module.exports = generateIconMaps;