const fs = require('fs');
const path = require('path');

// Define paths for source assets and generated map files
const assetsDir = path.join(__dirname, 'src', 'assets');
const iconMapJsPath = path.join(__dirname, 'src', 'iconMap.js');
const iconMapDartPath = path.join(__dirname, 'flutter_lib', 'lib', 'icon_map.dart');
const flutterAssetsDir = 'assets/icons'; // Relative path for Flutter assets within its package

/**
 * Generates icon map files for both JavaScript and Dart.
 * It reads asset filenames, converts them to PascalCase icon names,
 * and creates mappings to their respective relative paths.
 *
 * @returns {Promise<void>} A promise that resolves when both files are written, or rejects on error.
 */
async function generateIconMaps() {
  return new Promise((resolve, reject) => {
    fs.readdir(assetsDir, (err, files) => {
      if (err) {
        console.error('Error reading assets directory:', err);
        return reject(err);
      }

      let jsMapContent = 'export const iconMap = {\n';
      let dartMapContent = '/// This file is generated by generateIconMap.js. Do not modify directly.\n';
      dartMapContent += 'class IconMap {\n';
      dartMapContent += '  static const Map<String, String> iconMap = {\n';

      files.forEach(file => {
        const fileNameWithoutExt = file.split('.').slice(0, -1).join('.');
        // Convert filename to PascalCase for icon name (e.g., "my-icon.webp" -> "MyIcon")
        const iconName = fileNameWithoutExt
          .replace(/[^a-zA-Z0-9]+(.)?/g, (match, chr) => chr ? chr.toUpperCase() : '')
          .replace(/^./, (match) => match.toUpperCase()); // Ensure first char is uppercase

        // Add entry to JavaScript map
        jsMapContent += `  "${iconName}": () => import('./assets/${file}'),\n`;

        // Add entry to Dart map
        dartMapContent += `    '${iconName}': '${flutterAssetsDir}/${file}',\n`;
      });

      jsMapContent += '};';
      dartMapContent += '  };';
      dartMapContent += '}';

      const writePromises = [];

      // Write JavaScript iconMap.js
      writePromises.push(new Promise((res, rej) => {
        fs.writeFile(iconMapJsPath, jsMapContent, (err) => {
          if (err) {
            console.error('Error writing iconMap.js:', err);
            return rej(err);
          }
          console.log('iconMap.js generated successfully!');
          res();
        });
      }));

      // Write Dart icon_map.dart
      writePromises.push(new Promise((res, rej) => {
        fs.writeFile(iconMapDartPath, dartMapContent, (err) => {
          if (err) {
            console.error('Error writing icon_map.dart:', err);
            return rej(err);
          }
          console.log('icon_map.dart generated successfully!');
          res();
        });
      }));

      Promise.all(writePromises).then(resolve).catch(reject);
    });
  });
}

// Execute generateIconMaps if the script is run directly (e.g., via `node generateIconMap.js`)
if (require.main === module) {
  generateIconMaps().catch(error => {
    // Log error and exit with a non-zero code if generation fails
    console.error('Failed to generate icon maps:', error);
    process.exit(1);
  });
}

// Export the function for testing and programmatic use
module.exports = generateIconMaps;